language: python
python:
    - 2.7
virtualenv:
    system_site_packages: true
before_install:
    - sudo apt-get install gfortran libopenblas-dev liblapack-dev
    - sudo apt-get install python-numpy python-scipy
# command to install dependencies
install: 
    - travis_wait pip install -r requirements.txt
    - python setup.py build_ext --inplace
# command to run tests
script: nosetests
